pigman:
  spawn:
    chance: 10
    pack:
      minimum: 1
      maximum: 2
    biome:
      excludes:
      - Mesa Plateau
    limits:
      minimum_z: -4095
      maximum_z: -2000
      enabled: true
  attribute:
    health: 1.0
    speed:
      no_target: 0.21
      target_multiplier: 1.45
    knockback_resistance: 0.0
    damage: 10.0
    jump:
      multiplier: 1.05
    leap:
      multiplier: 0.45
  explode:
    adult:
      amount: 3
    baby:
      magnitude: 1.0
  babies: true
  drops:
  - ==: org.bukkit.inventory.ItemStack
    type: GOLD_INGOT
zombie:
  spawn:
    chance: 40
    pack:
      minimum: 1
      maximum: 2
    biome:
      excludes:
      - Mesa Plateau
    limits:
      minimum_z: 0
      maximum_z: 0
      enabled: false
  attribute:
    health: 20.0
    speed:
      no_target: 0.2
      target_multiplier: 1.4
    knockback_resistance: 0.0
    damage: 2.0
    jump:
      multiplier: 1.05
    leap:
      multiplier: 0.45
  type:
    normal:
      chance: 80
    leather:
      chance: 5
    chain:
      chance: 3
    gold:
      chance: 2
    iron:
      chance: 0
    explosive:
      chance: 3
  subtype:
    crawler:
      chance: 5
    jumper:
      chance: 5
  babies: true
  drops:
  - ==: org.bukkit.inventory.ItemStack
    type: PAPER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §rBandage
      lore:
      - §rStops bleeding.
      - §r
      - §r§eRight-click to use
      - §r§eLeft-click friend to use
  - ==: org.bukkit.inventory.ItemStack
    type: POTION
  - ==: org.bukkit.inventory.ItemStack
    type: IRON_FENCE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §rChain Links
guard:
  spawn:
    chance: 1
    pack:
      minimum: 1
      maximum: 1
    biome:
      excludes:
      - Mesa Plateau
    limits:
      minimum_z: 0
      maximum_z: 0
      enabled: false
  names:
  - Guard Forrest
  - Guard Aaron
  - Guard Brett
  - Guard Randall
  - Guard Lucian
  - Guard Kibo
  - Guard Jordan
  - Guard Edan
  - Guard Cadman
  - Guard Clinton
  - Guard Bevis
  - Guard Tyrone
  - Guard Aristotle
  - Guard Quamar
  - Guard Harding
  - Guard Todd
  - Guard Orlando
  - Guard Porter
  - Guard Mufutau
  - Guard Thane
  - Guard Gil
  - Guard Cooper
  - Guard Fulton
  - Guard Gavin
  - Guard Tobias
  - Guard Jared
  - Guard Tanner
  - Guard Abdul
  - Guard Porter
  - Guard Elton
  - Guard Zephania
  - Guard Jelani
  - Guard Dustin
  - Guard Boris
  - Guard Burke
  - Guard Emery
  - Guard Brock
  - Guard Kato
  - Guard Howard
  - Guard Aidan
  - Guard Neville
  - Guard Tad
  - Guard Hashim
  - Guard Amal
  - Guard Hilel
  - Guard Austin
  - Guard Jared
  - Guard Sean
  - Guard Burton
  - Guard Gray
  - Guard Victor
  - Guard Kamal
  - Guard Omar
  - Guard Gareth
  - Guard Steel
  - Guard Hunter
  - Guard Xavier
  - Guard Branden
  - Guard Silas
  - Guard Vaughan
  - Guard Cooper
  - Guard Adam
  - Guard Hakeem
  - Guard Hashim
  - Guard Hakeem
  - Guard Blaze
  - Guard Judah
  - Guard Forrest
  - Guard Nasim
  - Guard Ulric
  - Guard Dean
  - Guard Uriah
  - Guard Michael
  - Guard Malik
  - Guard Sebastian
  - Guard Nissim
  - Guard Nathaniel
  - Guard Yardley
  - Guard Nigel
  - Guard Cade
  - Guard Keith
  - Guard Rajah
  - Guard Cruz
  - Guard Keefe
  - Guard Steel
  - Guard Keefe
  - Guard Caldwell
  - Guard Mannix
  - Guard Wyatt
  - Guard Joshua
  - Guard Logan
  - Guard Ira
  - Guard Ciaran
  - Guard Giacomo
  - Guard Cruz
  - Guard Eagan
  - Guard Marvin
  - Guard Dolan
  - Guard Plato
  - Guard Nathaniel
  attribute:
    jump:
      multiplier: 1.05
    health: 25.0
    speed:
      no_target: 0.23
      target_multiplier: 1.0
    knockback_resistance: 0.0
    damage: 3.0
  equipment:
    melee:
      sword: IRON_SWORD
    boots: CHAINMAIL_BOOTS
    leggings: CHAINMAIL_LEGGINGS
    chestplate: CHAINMAIL_CHESTPLATE
    helmet: CHAINMAIL_HELMET
  become_zombie_on_death: true
  drops: []
  skins:
  - PhanaticD
  - Mooglemuffins
  - legit_craft
  - Polojp
  - Rising24
  - Arcticjelly
  - BradyM
  - Bambam423
  - Sophiehix
  - Ether3000
  - Rehtims
  - Shadysauce
  - Zeda_187
  - GabbyT
  - Hunterx
  - lRoixl
  - DoomLexus
  match_skins_to_names: false
giant:
  spawn:
    chance: 100
    pack:
      minimum: 1
      maximum: 1
    biome:
      excludes: []
      includes: []
    limits:
      minimum_z: -4095
      maximum_z: -3000
      enabled: true
  ability:
    reinforcement:
      minimum: 1
      maximum: 6
      chance: 30
    stomp:
      slowness:
        radius: 10
      magnitude: 1.5
  attribute:
    health: 100.0
    speed:
      no_target: 0.23
      target_multiplier: 1.5
    jump:
      multiplier: 4.1
    knockback_resistance: 0.0
    damage: 12.0
    leap:
      multiplier: 0.9
  drops:
  - ==: org.bukkit.inventory.ItemStack
    type: BOW
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      enchants:
        ARROW_INFINITE: 1
  - ==: org.bukkit.inventory.ItemStack
    type: DIAMOND_SWORD
    damage: 780
  - ==: org.bukkit.inventory.ItemStack
    type: GOLDEN_APPLE
general:
  spawn:
    biome:
      excludes:
      - Sky
      - Ocean
      - Deep Ocean
npc:
  lifetime_ticks: 600
horse:
  spawn:
    chance: 1
    pack:
      minimum: 1
      maximum: 1
    biome:
      excludes:
      - Mesa Plateau
  names:
  - Star
  - Dakota
  - Lucky
  - Blaze
  - Spirit
  - Freckles
  - Bo
  - Apache
  - Beauty
  - Belle
  - Bud
  - Honey
  - Lady
  - Rocky
  - Stormy
  - Toby
  - Prince
  - Molly
  - King
  - Maggie
  - Harley
  - Charlie
  - Chester
  - Charger
  - Champ
  attribute:
    speed:
      target_multiplier: 1.5
  is_cannibal: true
  mounted_undead:
    chance: 50
wolf:
  names:
  - Max
  - Jack
  - Rocky
  - Bear
  - Lucky
  - Maggie
  - Coco
  - Baxter
  - Sparky
  - Duke
  - Thor
  - Zeus
  - Winston
  - Heidi
  - Elsa
  - Anna
  - Sophie
  - Angus
  - Caesar
  - Quinn
  - Rufus
  - Anita
  - Ralph
  - Bubba
  - Hank
  spawn:
    chance: 1
    pack:
      minimum: 1
      maximum: 2
    biome:
      excludes:
      - Mesa Plateau
  is_cannibal: true
  mounted_undead:
    chance: 50
default_mobs:
  CREEPER:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SKELETON:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SPIDER:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SLIME:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  GHAST:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  ENDERMAN:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  CAVE_SPIDER:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SILVERFISH:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  BLAZE:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  MAGMA_CUBE:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  ENDER_DRAGON:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  WITHER:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  BAT:
    enabled: true
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  WITCH:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  ENDERMITE:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  GUARDIAN:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  PIG:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SHEEP:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  COW:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  CHICKEN:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SQUID:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  WOLF:
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
    enabled: false
  MUSHROOM_COW:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  SNOWMAN:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  OCELOT:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  IRON_GOLEM:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  HORSE:
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
    enabled: false
  RABBIT:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
  VILLAGER:
    enabled: false
    pathfinder:
      zombie: false
      pigman: false
      guard: false
      giant: false
mount_naturally:
  one_in: 100
