pigman:
  spawn:
    chance: 10
    pack:
      minimum: 1
      maximum: 2
    biome:
      excludes:
      - Mesa Plateau
    limits:
      minimum_z: -4095
      maximum_z: -2000
      enabled: true
  attribute:
    health: 1.0
    speed:
      no_target: 0.21
      target_multiplier: 1.45
    knockback_resistance: 0.0
    damage: 10.0
    jump:
      multiplier: 1.05
  explode:
    adult:
      amount: 3
    baby:
      magnitude: 1.0
  babies: true
zombie:
  spawn:
    chance: 50
    pack:
      minimum: 1
      maximum: 3
    biome:
      excludes:
      - Mesa Plateau
    limits:
      minimum_z: 0
      maximum_z: 0
      enabled: false
  attribute:
    health: 20.0
    speed:
      no_target: 0.23
      target_multiplier: 1.5
    knockback_resistance: 0.0
    damage: 3.0
    jump:
      multiplier: 1.05
  type:
    normal:
      chance: 80
    leather:
      chance: 5
    chain:
      chance: 3
    gold:
      chance: 2
    iron:
      chance: 0
  subtype:
    crawler:
      chance: 5
  babies: true
guard:
  spawn:
    chance: 1
    pack:
      minimum: 1
      maximum: 1
    biome:
      excludes:
      - Mesa Plateau
    limits:
      minimum_z: 0
      maximum_z: 0
      enabled: false
  names:
  - Guard Forrest
  - Guard Aaron
  - Guard Brett
  - Guard Randall
  - Guard Lucian
  - Guard Kibo
  - Guard Jordan
  - Guard Edan
  - Guard Cadman
  - Guard Clinton
  - Guard Bevis
  - Guard Tyrone
  - Guard Aristotle
  - Guard Quamar
  - Guard Harding
  - Guard Todd
  - Guard Orlando
  - Guard Porter
  - Guard Mufutau
  - Guard Thane
  - Guard Gil
  - Guard Cooper
  - Guard Fulton
  - Guard Gavin
  - Guard Tobias
  - Guard Jared
  - Guard Tanner
  - Guard Abdul
  - Guard Porter
  - Guard Elton
  - Guard Zephania
  - Guard Jelani
  - Guard Dustin
  - Guard Boris
  - Guard Burke
  - Guard Emery
  - Guard Brock
  - Guard Kato
  - Guard Howard
  - Guard Aidan
  - Guard Neville
  - Guard Tad
  - Guard Hashim
  - Guard Amal
  - Guard Hilel
  - Guard Austin
  - Guard Jared
  - Guard Sean
  - Guard Burton
  - Guard Gray
  - Guard Victor
  - Guard Kamal
  - Guard Omar
  - Guard Gareth
  - Guard Steel
  - Guard Hunter
  - Guard Xavier
  - Guard Branden
  - Guard Silas
  - Guard Vaughan
  - Guard Cooper
  - Guard Adam
  - Guard Hakeem
  - Guard Hashim
  - Guard Hakeem
  - Guard Blaze
  - Guard Judah
  - Guard Forrest
  - Guard Nasim
  - Guard Ulric
  - Guard Dean
  - Guard Uriah
  - Guard Michael
  - Guard Malik
  - Guard Sebastian
  - Guard Nissim
  - Guard Nathaniel
  - Guard Yardley
  - Guard Nigel
  - Guard Cade
  - Guard Keith
  - Guard Rajah
  - Guard Cruz
  - Guard Keefe
  - Guard Steel
  - Guard Keefe
  - Guard Caldwell
  - Guard Mannix
  - Guard Wyatt
  - Guard Joshua
  - Guard Logan
  - Guard Ira
  - Guard Ciaran
  - Guard Giacomo
  - Guard Cruz
  - Guard Eagan
  - Guard Marvin
  - Guard Dolan
  - Guard Plato
  - Guard Nathaniel
  attribute:
    jump:
      multiplier: 1.05
    health: 25.0
    speed:
      no_target: 0.23
      target_multiplier: 1.0
    knockback_resistance: 0.0
    damage: 3.0
  equipment:
    melee:
      sword: IRON_SWORD
    boots: CHAINMAIL_BOOTS
    leggings: CHAINMAIL_LEGGINGS
    chestplate: CHAINMAIL_CHESTPLATE
    helmet: CHAINMAIL_HELMET
  become_zombie_on_death: true
giant:
  spawn:
    chance: 100
    pack:
      minimum: 1
      maximum: 1
    biome:
      excludes:
      - Ocean
      includes:
      - Mesa Plateau
    limits:
      minimum_z: -4095
      maximum_z: -3000
      enabled: true
  ability:
    reinforcement:
      minimum: 1
      maximum: 6
      chance: 30
    stomp:
      slowness:
        radius: 10
      magnitude: 1.5
  attribute:
    health: 100.0
    speed:
      no_target: 0.23
      target_multiplier: 1.5
    jump:
      multiplier: 4.1
    knockback_resistance: 0.0
    damage: 12.0
general:
  spawn:
    biome:
      excludes:
      - Sky
      - Ocean
      - Deep Ocean
npc:
  lifetime_ticks: 600
default_mobs:
  CREEPER: false
  SKELETON: false
  SPIDER: false
  SLIME: false
  GHAST: false
  ENDERMAN: false
  CAVE_SPIDER: false
  SILVERFISH: false
  BLAZE: false
  MAGMA_CUBE: false
  ENDER_DRAGON: false
  WITHER: false
  BAT: false
  WITCH: false
  ENDERMITE: false
  GUARDIAN: false
  PIG: false
  SHEEP: false
  COW: false
  CHICKEN: false
  SQUID: false
  WOLF: false
  MUSHROOM_COW: false
  SNOWMAN: false
  OCELOT: false
  IRON_GOLEM: false
  HORSE: false
  RABBIT: false
  VILLAGER: false
