visibility:
  player:
    walking: 3
    sprinting: 6
    airborne: 2
    activate_redstone: 0
    take_damage: 2
    shooting: 1
    sneaking: -2
    holding_flesh: -1
    wearing_zombie_head: -3
    base: 3
    bleeding: 2
    chat: 1
    on_fire: 7
    in_grass: -5
    crackshot:
      Bazooka:
        shoot: 7
        reload: 2
      Olympia:
        shoot: 7
        reload: 2
      Riotshield:
        shoot: 7
        reload: 2
      Python:
        shoot: 7
        reload: 2
      CocoPops:
        shoot: 7
        reload: 2
      M320:
        shoot: 7
        reload: 2
      C4:
        shoot: 7
        reload: 2
      Trinket:
        shoot: 7
        reload: 2
      Gauss:
        shoot: 7
        reload: 2
      Carbine:
        shoot: 7
        reload: 2
      Airstrike:
        shoot: 7
        reload: 2
      Grenade:
        shoot: 7
        reload: 2
      Hunting:
        shoot: 7
        reload: 2
      AK-47:
        shoot: 7
        reload: 2
      Putty:
        shoot: 7
        reload: 2
      Toaster:
        shoot: 7
        reload: 2
      Tactical_Knife:
        shoot: 7
        reload: 2
      Flashbang:
        shoot: 7
        reload: 2
      Deagle:
        shoot: 7
        reload: 2
      Type95:
        shoot: 7
        reload: 2
    in_dark: -3
    in_vehicle: 4
    in_diamond: 2
    in_gold: 2
    in_iron: 1
    in_chainmail: 1
    in_leather: -1
  environment:
    explosion: 6
    arrow_landed: 4
    snowball_landed: 5
  stretch: 32.0
  eating: 1
  drinking: 1
thirst:
  max:
    default: 20
  decay:
    beach: 20
    plains: 38
    taiga: 40
    desert: 23
    ocean: -120
    jungle: 31
    mesa: 30
    mushroom: 50
    swamp: 49
    modifier:
      per_dehydrated_level: -4
chat:
  local:
    radius: 50
  autocorrect: false
death:
  vulnerable_time: 300
  revive_time: 10
  transition_time: 60
bleed:
  damage_delay: 42
  damage_amount: 0.2
infection:
  damage_delay: 38
  damage_amount: 0.1
equipment:
  devastated_modifier: 50
  shattered_modifier: 40
  broken_modifier: 70
  slack_modifier: 90
  reinforced_modifier: 110
  cracked_modifier: 80
  precise_modifier: 120
  bow_sharpened:
    ranged_modifier: 150
    combat_modifier: 5
  weakened_modifier: 85
  dull_modifier: 90
  sharpened_modifier: 130
  tempered_modifier: 150
  fortified_modifier: 120
  ornate_modifier: 150
  upgrade:
    material_cost: 6
  bow_precise:
    headshot_modifier: 4
heal:
  bandage:
    amount: 16.0
  time_to_complete: 15
  time_to_cooldown: 300
  default:
    heal:
      duration: 5
      level: 0
    absorption:
      duration: 0
      level: 0
    antiseptic: false
  medicine:
    heal:
      extention: 5
      level: 1
    absorption:
      extention: 20
      level: 1
    antiseptic: true
  ointment:
    heal:
      extention: 3
      level: 0
    absorption:
      extention: 8
      level: 0
    antiseptic: false
  antiseptic:
    heal:
      extention: 0
      level: 0
    absorption:
      extention: 0
      level: 0
    antiseptic: true
temperature:
  default: 37.0
  biome:
    frozen: 31.0
    cold: 35.5
    medium: 37.0
    warm: 39.9
    ocean: 30.5
    fourth_dimension: 30.1
  modify:
    thirst:
      threshold: 3.0
      thirsty: 0.5
    water:
      in_non_ocean_water: -2.2
    downfall: -1.6
    player:
      on_fire: 15.0
    armour_per_piece:
      leather: 0.3
      chainmail: 0.11
      iron: 0.15
      gold: 0.21
      diamond: 0.27
    infected: 2.1
    sprinting: 0.9
    nighttime: -1.2
    warm_water: 0.5
    cold_water: -0.9
    on_mountain:
      y_threshold: 110.0
      modifier: -0.15
    near_fire: 300.2
    holding:
      torch: 60.1
      ice: -30.2
      snow: -25.1
      lava_bucket: 100.2
    near_torch: 100.2
    near_burning_furnace: 40.2
    near_snow: -5.1
  threshold:
    heatstroke:
      '3': 42.7
      '2': 40.6
      '1': 39.2
    sweating: 38.2
    shivering: 35.8
    hypothermia:
      '1': 34.8
      '2': 33.4
      '3': 32.3
  heatstroke:
    damage_per_level: 1.0
  hypothermia:
    damage_per_level: 1.0
  execute_after_delay:
    damage: 40
    frostbite: 62
    potion_effects: 33
    sweat: 3
  modifier:
    near_snow: -5.1
  minimum: 50.5
  maximum: 147.3
chest:
  respawn_time: 300
airdrop:
  break_blocks: false
  create_wreckage: false
  set_fires: false
  explosion_magnitude: 2.0
  chest_types:
  - Supplies - Rare
  - Weaponry - Rare
  - Armor - Rare
  - Food - Rare
spawnkit:
  hierarchical: false
spawn:
  safespawn_radius: 15
  clear_inventory: true
  clear_armor: true
hologram:
  display_ticks: 1
  display:
    time: 3
points:
  death: 0.1
  kill:
    zombie: 1.0
    pigman: 0.5
    giant: 12.0
    player: 3.0
    guard: 0.8
  drink: 0.05
  friend_add: 0.0
  heal:
    self: 0.5
    other: 3.0
    infection: 0.5
  revive:
    other: 3.0
    self: 0.7
  ghost: 0.2
  undead: 0.25
chests:
  random_layout: true
ghosts:
  can_damage: false
zombie_awareness_month:
  enabled: false
specialevent:
  zombie_awareness_month:
    strength_multiplier: 2.0
    health_multiplier: 2.0
    detection_multiplier: 2.0
    zombify: false
    enabled: false
  april_fools:
    enabled: false
  easter:
    enabled: false
  speak_like_pirate:
    enabled: false
friends:
  friendly_fire: false
safe_logout:
  timer: 10
  completed_command: kick $player hubkick
scoreboard:
  highscore:
    data:
    - '&4Zombie Kills: &r%kills.zombie.owner% &r&4- &e%kills.zombie.value%'
    - '&4Player Kills: &r%kills.player.owner% &r&4- &e%kills.player.value%'
    - '&4Pigman Kills: &r%kills.pigman.owner% &r&4- &e%kills.pigman.value%'
    - '&4Giant Kills: &r%kills.giant.owner% &r&4- &e%kills.giant.value%'
    - '&4Guard Kills: &r%kills.guard.owner% &r&4- &e%kills.guard.value%'
    - '&4Friends: &r%friends.owner% &r&4- &e%friends.value%'
    - '&4Drinks: &r%drinks.owner% &r&4- &e%drinks.value%'
    - '&4Deaths: &r%deaths.owner% &r&4- &e%deaths.value%'
    - '&4zPoints: &r%z_points.owner% &r&4- &e%z_points.value%'
  name: '&4MyZ Stats - Career Kills@&4MyZ Stats - Current Kills@&4MyZ Stats - Status@&4MyZ
    Stats - Levels@&4MyZ Stats - Deaths@&4MyZ Stats - Other@&4MyZ Stats - Highscores'
  data: Players Killed:%kills.player%,Zombies Killed:%kills.zombie%,Pigmen Killed:%kills.pigman%,Giants Killed:%kills.giant%@Players Killed:%tracked.kills.player%,Zombies Killed:%tracked.kills.zombie%,Pigmen Killed:%tracked.kills.pigman%,Giants Killed:%tracked.kills.giant%@Bleeding:%bleeding%,Poisoned:%poisoned%,Temperature:%temperature%,Thirst:%thirst%@Wolf Level:%wolf.level%,Horse Level:%horse.level%,Immunity Level:%immunity%,Toughness Level:%toughness%@Zombie:%killer.zombie%,Pigman:%killer.pigman%,Giant:%killer.giant%,Guard%killer.guard%,Projectile:%killer.projectile%,Fire:%killer.fire%,Falling:%killer.fall%,Drown:%killer.drown%,Void:%killer.void%,Magic:%killer.magic%,Starvation:%killer.hunger%,Explode:%killer.explode%,Other:%killer.other%@Friends:%friends%,Revives:%revives.other%,Drinks Consumed:%drinks%,Deaths:%deaths%,Bandages Used:%heals.self.infection%,Heals:%heals.other%,zPoints:%z_points%@Zombie Kills:%highscore.kills.zombie%,Player Kills:%highscore.kills.player$,Pigman Kills:%highscore.kills.pigman%,Giant Kills:%highscore.kills.giant%,Guard Kills:%highscore.kills.guard%
spawn_title:
  fadein_time: 5
  display_time: 60
  fadeout_time: 5
rank:
  load_forwards: true
followers:
  points:
    death_penalty: 0.2
    damage_entity: 0.1
    multiplier_per_level: 0.43
    fireworks_on_levelup: true
mobs:
  pig:
    zombification: true
dedicated:
  auto-respawn: false
ender_travel_chance: 3
camouflaged_duration: 20
grenade_magnitude: 1.0
grenade_magnitude_maximum: 9.0
